// frontend/src/components/CategoryIcons.js
import {
    Devices,
    Checkroom,
    Kitchen,
    MenuBook,
    Weekend,
    Toys,
    Diamond,
    SportsSoccer,
    DirectionsCar,
    MusicNote,
    Brush,
    Spa,
    Grass,
    BusinessCenter,
    Pets,
    SportsEsports,
    Movie,
    ChildCare,
    Build,
    PhotoCamera,
    Smartphone,
    Laptop,
    Tablet,
    Watch,
    DirectionsRun,
    LocalGroceryStore,
    Create,
    WbIncandescent,
    Hotel,
    Restaurant,
    FitnessCenter,
    Code,
    Event,
    PedalBike,
    SportsBasketball,
    Construction,
    EmojiNature,
    Public,
    LocalFlorist ,
    HelpOutline,
} from '@mui/icons-material';

export const icons = {
    'Uncategorized': HelpOutline,
    'Electronics': Devices,
    'Clothing': Checkroom,
    'Home Appliances': Kitchen,
    'Books': MenuBook,
    'Furniture': Weekend,
    'Toys & Games': Toys,
    'Jewelry': Diamond,
    'Sports Equipment': SportsSoccer,
    'Automotive': DirectionsCar,
    'Musical Instruments': MusicNote,
    'Art & Collectibles': Brush,
    'Health & Beauty': Spa,
    'Garden & Outdoor': Grass,
    'Office Supplies': BusinessCenter,
    'Pet Supplies': Pets,
    'Video Games': SportsEsports,
    'Movies & DVDs': Movie,
    'Baby Products': ChildCare,
    'Tools & Hardware': Build,
    'Cameras & Photography': PhotoCamera,
    'Mobile Phones': Smartphone,
    'Laptops': Laptop,
    'Tablets': Tablet,
    'Watches': Watch,
    'Shoes': DirectionsRun,
    'Handbags': BusinessCenter,
    'Groceries': LocalGroceryStore,
    'Stationery': Create,
    'Lighting': WbIncandescent,
    'Bedding': Hotel,
    'Kitchenware': Restaurant,
    'Fitness Equipment': FitnessCenter,
    'Software': Code,
    'Tickets & Experiences': Event,
    'Bicycles': PedalBike,
    'Board Games': SportsBasketball,
    'Craft Supplies': Create,
    'Hobbies': EmojiNature,
    'Antiques': Public,
    'Building Materials': Construction,
    'Cosmetics': Spa,
    'Luxury Items': Diamond,
    'Travel Accessories': DirectionsCar,
    'Costumes': Checkroom,
    'Musical Records': MusicNote,
    'Car Accessories': DirectionsCar,
    'Drones': PhotoCamera,
    'Smart Home Devices': Devices,
    'Eco-friendly Products': LocalFlorist ,
};
