# Generated by Django 5.1.4 on 2025-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
