# Generated by Django 5.1.6 on 2025-02-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='auction_item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
