# Generated by Django 5.1.6 on 2025-02-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_orderitem_order_remove_orderitem_auction_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
