# Generated by Django 5.1.6 on 2025-02-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auctionitem_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='is_paid',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
