# Generated by Django 5.1.6 on 2025-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_transaction_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='shipping_status',
            field=models.CharField(choices=[('not_shipped', 'Not Shipped'), ('shipped', 'Shipped'), ('received', 'Received')], default='not_shipped', max_length=20),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
