# Generated by Django 5.2.6 on 2025-11-06 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['status', 'end_time'], name='auctions_au_status_c82cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['owner'], name='auctions_au_owner_i_efb9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['winner'], name='auctions_au_winner__3936ec_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction_item', 'amount'], name='auctions_bi_auction_d53cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder'], name='auctions_bi_bidder__19a36e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'recipient', 'timestamp'], name='auctions_ch_sender__c1c33c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='auctions_no_user_id_4d0ad1_idx'),
        ),
    ]
